name: DrivingCar
channels:
  - defaults
dependencies:
  - ffmpeg
  - h5py
  - numpy
  - opencv
  - pip
  - py-opencv
  - python=3.*
  - tensorflow
  - ipykernel
  - matplotlib
  - nomkl
  - pandas
  - pip:
    - eventlet
    - flask
    - pillow
    - python-socketio